#include "gen.h"

#include "../parser/error.h"
#include "layout.h"
#include "scope.h"
#include "settings.h"
#include "util.h"

#define EXPLAIN(cbref, indent, ...)                          \
    do {                                                     \
        if (add_explanatory_comments) {                      \
            cb_add_back(&(cbref), indent, "; " __VA_ARGS__); \
        }                                                    \
    } while (0)

#define EXPLAIN_NL(cbref)                \
    do {                                 \
        if (add_explanatory_comments) {  \
            cb_add_back(&(cbref), 0, "\n"); \
        }                                \
    } while (0)

static cb_t gen_program(int indent, const struct program_node_t *node);
static cb_t gen_global_variable_decl(
    int indent, const struct global_variable_declaration_node_t *node);
static cb_t gen_extern_decl(int                                     indent,
                            const struct extern_declaration_node_t *node);
static cb_t gen_layout_decl(int                                     indent,
                            const struct layout_declaration_node_t *node);

struct scope_t global_scope;

cb_t gen(struct program_node_t *prog) {
    cb_t res;
    cb_init(&res);

    log_debug("Initializing global scope\n");
    scope_init(&global_scope);

    EXPLAIN(res, 0, "NASM generated by bbb for this program begins here.\n");

    cb_t other = gen_program(0, prog);
    if (!cb_is_valid(&other)) {
        return other;
    }
    cb_glue_back(&res, &other);

    EXPLAIN(res, 0, "NASM generated by bbb for this program ends here.\n");
    scope_destroy(&global_scope);

    return res;
}

static cb_t gen_program(int indent, const struct program_node_t *node) {
    log_debug("Entered with indent=%d\n", indent);
    log_assert(node != NULL);

    cb_t res;
    cb_init(&res);

    if (node->rest != NULL) {
        cb_t other = gen_program(indent, node->rest);
        if (!cb_is_valid(&other)) {
            return other;
        }
        cb_glue_back(&res, &other);
    }

    if (node->gvar_decl != NULL) {
        cb_t other = gen_global_variable_decl(indent, node->gvar_decl);
        if (!cb_is_valid(&other)) {
            return other;
        }
        cb_glue_back(&res, &other);
    } else if (node->layout_decl != NULL) {
        cb_t other = gen_layout_decl(indent, node->layout_decl);
        if (!cb_is_valid(&other)) {
            return other;
        }
        cb_glue_back(&res, &other);
    } else if (node->ext_decl != NULL) {
        cb_t other = gen_extern_decl(indent, node->ext_decl);
        if (!cb_is_valid(&other)) {
            return other;
        }
        cb_glue_back(&res, &other);
    } else if (node->fn_decl != NULL) {
        // todo
    } else if (node->nasm_b != NULL) {
        // todo
    }

    return res;
}

static cb_t gen_global_variable_decl(
    int indent, const struct global_variable_declaration_node_t *node) {
    log_debug("Entered with indent=%d\n", indent);
    log_assert(node != NULL);

    cb_t res;
    cb_init(&res);

    int    is_global = 0;
    size_t mem_len = 8;
    size_t align = 8;

    if (node->vis != NULL) {
        const char *vis = util_get_visibility(node->vis);
        if (vis != NULL && strcmp(vis, "global") == 0) {
            is_global = 1;
        } else {
            return cb_invalid();
        }
    }
    log_debug(" - global: %d\n", is_global);

    if (node->mem_len != NULL && util_get_mem_len(node->mem_len, &mem_len)) {
        return cb_invalid();
    }
    log_debug(" - mem_len: %zu\n", mem_len);

    if (node->align != NULL && util_get_align(node->align, &align)) {
        return cb_invalid();
    }
    log_debug(" - align: %zu\n", align);

    EXPLAIN(res, indent, "This is a global variable '%s'.\n", node->name->name);
    cb_add_back(&res, indent, "section .bss\n");
    if (is_global == 1) {
        cb_add_back(&res, indent + CB_TAB, "global %s\n", node->name->name);
    }

    cb_add_back(&res, indent + CB_TAB, "alignb %zu\n", align);
    cb_add_back(&res, indent + CB_TAB, "%s: resb %zu\n", node->name->name, mem_len);
    cb_add_back(&res, 0, "\n");

    if (scope_has(&global_scope, node->name->name)) {
        log_debug(" - symbol already in the global scope.\n");
        context_msg(&node->name->frag,
                    "Error: the compiler is already aware of this symbol.\n");
        return cb_invalid();
    }

    struct location_t loc;
    loc_init_symbol(&loc, node->name->name, 0);
    log_debug(" - adding location to global scope.\n");
    scope_add(&global_scope, node->name->name, loc);

    return res;
}

static cb_t gen_extern_decl(int                                     indent,
                            const struct extern_declaration_node_t *node) {
    log_debug("Entered with indent=%d\n", indent);
    log_assert(node != NULL);

    cb_t res;
    cb_init(&res);

    if (strcmp(node->kw->name, "extern") == 0) {
        log_debug("Generating extern declaration for '%s'\n", node->name->name);

        EXPLAIN(res, indent, "Extern daclaration.\n");

        char *line =
            (char *)malloc(strlen("extern ") + strlen(node->name->name) + 1 + 1);
        log_assert(line != NULL);

        strcpy(line, "extern ");
        strcat(line, node->name->name);
        log_debug(" - appending '%s'\n", line);
        strcat(line, "\n");
        cb_add_back(&res, indent, line);
        free(line);

        if (scope_has(&global_scope, node->name->name)) {
            log_debug(" - symbol already in the global scope.\n");
            context_msg(&node->name->frag,
                        "Note: the compiler is already aware of this symbol.\n");
            return res;
        }

        struct location_t loc;
        loc_init_symbol(&loc, node->name->name, 0);
        log_debug(" - adding location to global scope.\n");
        scope_add(&global_scope, node->name->name, loc);

        return res;
    } else if (strcmp(node->kw->name, "nasm") == 0) {
        log_debug("Generating nasm declaration\n");

        if (scope_has(&global_scope, node->name->name)) {
            log_debug(" - symbol already in the global scope.\n");
            context_msg(&node->name->frag,
                        "Note: the compiler is already aware of this symbol.\n");
            return res;
        }

        struct location_t loc;
        loc_init_symbol(&loc, node->name->name, 0);
        log_debug(" - adding location to global scope.\n");
        scope_add(&global_scope, node->name->name, loc);

        return res;
    } else {
        context_msg(&node->frag, "Unknown declaration (wrong keyword)\n");
        return cb_invalid();
    }
}

static cb_t gen_layout_decl(int                                     indent,
                            const struct layout_declaration_node_t *node) {
    log_debug("Entered with indent=%d\n", indent);
    log_assert(node != NULL);

    cb_t res;
    cb_init(&res);

    if (layouts_has(node->name->name) == 1) {
        context_msg(&node->name->frag,
                    "Error: layout with the same name already exists.\n");
        return cb_invalid();
    }

    size_t          mem_len;
    struct layout_t layout = {0};

    // first pass for n and total_size
    struct layout_declaration_items_node_t *items = node->items;

    while (items != NULL) {
        if (items->mem_len != NULL && util_get_mem_len(items->mem_len, &mem_len)) {
            return cb_invalid();
        }
        layout.total_size += mem_len;
        if (strcmp(items->name->name, "_") != 0) {
            layout.n++;
        }

        items = items->rest;
    }

    // second pass
    log_debug(" - fields without paddings: %zu\n", layout.n);
    log_debug(" - total size: %zu\n", layout.total_size);
    items = node->items;
    layout.fields = (const char **)malloc(sizeof(const char *) * layout.n);
    log_assert(layout.fields != NULL);
    layout.offsets = (size_t *)malloc(sizeof(const char *) * layout.total_size);
    log_assert(layout.offsets != NULL);

    size_t n = layout.n;
    layout.n = 0;
    size_t i = 0;
    size_t offset = 0;

    EXPLAIN(res, indent, "Layout '%s' is defined as:\n", node->name->name);
    while (items != NULL) {
        if (items->mem_len != NULL && util_get_mem_len(items->mem_len, &mem_len)) {
            return cb_invalid();  // cant happen but ok
        }
        if (layout_has_field(&layout, items->name->name) == 1) {
            context_msg(&items->name->frag, "Error: duplicate layout field.\n");
            free(layout.fields);
            free(layout.offsets);
            return cb_invalid();
        }
        if (strcmp(items->name->name, "_") != 0) {
            layout.fields[i] = items->name->name;
            layout.offsets[i] = offset;
            EXPLAIN(res, indent + CB_TAB, "field '%s' of size %zub at offset +%zu\n",
                    layout.fields[i], mem_len, offset);
            log_debug(" - field '%s' of %zub at +%zu\n", items->name->name, mem_len,
                      offset);
            layout.n++;
        } else {
            log_debug(" - padding of %zub at +%zu\n", mem_len, offset);
            EXPLAIN(res, indent + CB_TAB, "padding of size %zub at offset +%zu\n",
                    mem_len, offset);
        }
        offset += mem_len;

        i++;
        items = items->rest;
    }
    EXPLAIN_NL(res);
    log_assert(layout.n == n);

    layouts_register(node->name->name, layout);
    log_debug(" - registered the layout.\n");

    return res;
}
