#include "gen.h"
#include "../parser/error.h"

#include "settings.h"

#define EXPLAIN(cbref, indent, msg)                  \
    do {                                             \
        if (add_explanatory_comments) {              \
            cb_add_back(&(cbref), indent, "; " msg); \
        }                                            \
    } while (0)

static cb_t gen_extern_decl(int                                     indent,
                            const struct extern_declaration_node_t *node);
static cb_t gen_program(int indent, const struct program_node_t *node);

cb_t gen(struct program_node_t *prog) {
    cb_t res;
    cb_init(&res);

    EXPLAIN(res, 0, "NASM generated by bbb for this program begins here.\n");

    cb_t other = gen_program(0, prog);
    if (!cb_is_valid(&other)) {
        return other;
    }
    cb_glue_back(&res, &other);

    EXPLAIN(res, 0, "NASM generated by bbb for this program ends here.\n");
    return res;
}

static cb_t gen_program(int indent, const struct program_node_t *node) {
    log_debug("Entered with indent=%d\n", indent);
    log_assert(node != NULL);

    cb_t res;
    cb_init(&res);

    if (node->rest != NULL) {
        // todo
    }

    if (node->gvar_decl != NULL) {
        // todo
    }
    else if (node->layout_decl != NULL) {
        // todo
    }
    else if (node->ext_decl != NULL) {
        cb_t other = gen_extern_decl(indent, node->ext_decl);
        if (!cb_is_valid(&other)) {
            return other;
        }
        cb_glue_back(&res, &other);
    }
    else if (node->fn_decl != NULL) {
        // todo
    }
    else if (node->nasm_b != NULL) {
        // todo
    }

    return res;
}

static cb_t gen_extern_decl(int indent, const struct extern_declaration_node_t *node) {
    log_debug("Entered with indent=%d\n", indent);
    log_assert(node != NULL);

    cb_t res;
    cb_init(&res);

    if (strcmp(node->kw->name, "extern") == 0) {
        log_debug("Generating extern declaration\n");
        EXPLAIN(res, indent, "Extern daclaration.\n");

        char *line = (char*)malloc(strlen("extern ") + strlen(node->name->name) + 1 + 1);
        log_assert(line != NULL);

        strcpy(line, "extern ");
        strcat(line, node->name->name);
        log_debug(" - appending '%s'\n", line);
        strcat(line, "\n");
        cb_add_back(&res, indent, line);
        free(line);

        return res;
    }
    else if (strcmp(node->kw->name, "nasm") == 0) {
        // todo
        return res;
    }
    else {
        context_msg(&node->frag, "Unknown declaration (wrong keyword)");
        return cb_invalid();
    }
}
